services:
  postgres:
    image: "postgres:latest"
    environment:
      POSTGRES_DB: "${POSTGRES_DB:-mydatabase}"
      POSTGRES_USER: "${POSTGRES_USER:-myuser}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-secret}"
    ports:
      - "${POSTGRES_PORT:-5432}:5432"

  redis:
    image: "redis:latest"
    ports:
      - "${REDIS_PORT:-6379}:6379"