spring:
  application:
    name: scheduler
  jackson:
    property-naming-strategy: SNAKE_CASE

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

scheduler:
  instance-policy:
    # hard timeout 상한 기본값
    max-hard-timeout-minutes: 360
